services:
  # Image file name
  pythonsucks-discordbot:
    build: .
    container_name: pythonsucksbot

    # Inject secrets at runtime (not baked into the image)
    env_file: settings.env

    # Restart policy: keep the bot alive across crashes and reboots
    restart: always

    # Mount DATA ONLY so CSV updates don't require rebuilds.
    # On the host (Pi), ./data maps to /botapp/data inside the container.
    volumes:
      - ./data:/botapp/data:rw
    
    # Lavalink dependency
    depends_on:
      - lavalink
  
  lavalink:
    image: ghcr.io/freyacodes/lavalink:latest
    container_name: lavalink
    restart: always
    ports:
      - "2333:2333" # expose if external needed
    env_file:
      - settings.env
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml


    # Optional healthcheck to ensure the container is "healthy"
    # (uncomment and adapt to your bot if you expose a health endpoint or add a small script)
    # healthcheck:
    #   test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('discord.com', 443)); s.close()"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5