server:
  port: 2333   # Lavalink's internal port
  address: 0.0.0.0  # Listen on all interfaces

lavalink:
  plugins:
    # Replace VERSION with the current version as shown by the Releases tab or a long commit hash for snapshots.
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.14.0"
      snapshot: false # Set to true if you want to use a snapshot version.
  server:
    password: ${LAVALINK_PASSWORD} 
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true

# Optional: Logging settings (keep minimal for Pi)
logging:
  level:
    root: INFO
    lavalink: INFO

