server:
  port: 2333   # Lavalink's internal port
  address: 0.0.0.0  # Listen on all interfaces

lavalink:
  server:
    password: Doughnuts12 #${LAVALINK_PASSWORD}   # <-- must match your bot's Wavelink config
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true

# Optional: Logging settings (keep minimal for Pi)
logging:
  level:
    root: INFO
    lavalink: INFO

